language: php

sudo: false

php:
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_install:
    - nvm install node

install:
    - npm install
    - composer install

script:
    - node -v
    - bin/phpunit
