language: php

sudo: false

php:
    - 7.0

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

install:
    - npm n -g
    - n 6.2
    - npm install
    - composer install

script:
    - bin/phpunit
