language: php

php:
    - 7.0

matrix:
    allow_failures:
        - php: hhvm
        - php: 7.0

install:
    - sudo npm install n -g
    - sudo n 6.2
    - npm install
    - composer install

script:
    - bin/phpunit
