services:
    incsw_assetic_extensions.filter.babel:
        class: IncSW\AsseticExtensionsBundle\Assetic\Filter\BabelFilter
        arguments:
            - %assetic.node.bin%
            - %incsw_assetic_extensions.filter.babel.config%
            - %assetic.node.paths%
        cals:
            - [setTimeout, [null]]
        tags:
            - { name: assetic.filter, alias: babel }
